# This file was generated by GoReleaser. DO NOT EDIT.
cask "cruft" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "60d36f129976ab36939dbedc0f03510593b99626154be6f2870dbd68a72ce233"
      url "https://github.com/sachincool/cruft/releases/download/v#{version}/cruft_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0fca82ad9a8652bb365f9aba24abc34367f88dc51a5eab207ef47edea5792e0d"
      url "https://github.com/sachincool/cruft/releases/download/v#{version}/cruft_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "cruft"
  desc "Decruft your dev laptop. 25 cleaners, deletes on confirm, --safe for 7-day undo."
  homepage "https://github.com/sachincool/cruft"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cruft"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cruft"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    cruft is macOS-only for now.
      cruft                 # interactive TUI
      cruft run --all       # non-interactive
      cruft glossary        # define every term cruft uses
    Audit logs: ~/.local/share/cruft/runs/
    Recycle (--safe only):   ~/.local/share/cruft/tombstone/
  EOS
end
