# This file was generated by GoReleaser. DO NOT EDIT.
cask "cruft" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "4f5e833be47a77e3074b5e6abbe2e213457ce880ef116ac15d16c235149c321e"
      url "https://github.com/sachincool/cruft/releases/download/v#{version}/cruft_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1e88e6c3ac656dcf0380e7a3a503c19b5eea62dc39f61f766b5ff787a6d7ae10"
      url "https://github.com/sachincool/cruft/releases/download/v#{version}/cruft_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "cruft"
  desc "Decruft your dev laptop. 25 cleaners, deletes on confirm, --safe for 7-day undo."
  homepage "https://github.com/sachincool/cruft"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cruft"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cruft"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    cruft is macOS-only for now.
      cruft                 # interactive TUI
      cruft run --all       # non-interactive
      cruft glossary        # define every term cruft uses
    Audit logs: ~/.local/share/cruft/runs/
    Recycle (--safe only):   ~/.local/share/cruft/tombstone/
  EOS
end
