# This file was generated by GoReleaser. DO NOT EDIT.
cask "cruft" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "0bd81ad18c6136fe5f2499f8de3d9d037eee9941b936ff5e194689502e434fa8"
      url "https://github.com/sachincool/cruft/releases/download/v#{version}/cruft_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "efaaa551efc4f642eaab5097e4a35687e5b357578e08b4d3d3d3b155dcb95e96"
      url "https://github.com/sachincool/cruft/releases/download/v#{version}/cruft_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "cruft"
  desc "Decruft your dev laptop. 25 cleaners, deletes on confirm, --safe for 7-day undo."
  homepage "https://github.com/sachincool/cruft"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cruft"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cruft"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    cruft is macOS-only for now.
      cruft                 # interactive TUI
      cruft run --all       # non-interactive
      cruft glossary        # define every term cruft uses
    Audit logs: ~/.local/share/cruft/runs/
    Recycle (--safe only):   ~/.local/share/cruft/tombstone/
  EOS
end
